image: registry.cn-shanghai.aliyuncs.com/c7n/cibase:0.9.1

stages:
  - build
  - release

build front:
  stage: build
  script:
    - npm install --registry ${NPM_REPO} --sass-binary-site=http://npm.taobao.org/mirrors/node-sass
    - chmod -R 755 node_modules
    - npm run compile
    - echo "//${NPM_REGISTRY}:_authToken=${NPM_TOKEN}">.npmrc
    - npm publish --registry https://nexus.choerodon.com.cn/repository/private-npm/
    - curl -sX POST -F token=${FRONT_REPOSITORY_TOKEN} -F ref=${REF_NAME} https://code.choerodon.com.cn/api/v4/projects/7909/trigger/pipeline
  except:
    changes:
      - .circleci/**/*
      - .gitignore
      - .github/**/*
      - .gitlab-ci.yml
      - "*.md"
    variables:
      - $CI_COMMIT_MESSAGE =~ /combine/

tag front:
  stage: build
  script:
    - npm install --registry ${NPM_REPO} --sass-binary-site=http://npm.taobao.org/mirrors/node-sass
    - chmod -R 755 node_modules
    - npm run compile
    - echo "//${NPM_REGISTRY}:_authToken=${NPM_TOKEN}">.npmrc
    - npm publish --registry https://nexus.choerodon.com.cn/repository/private-npm/
  only:
    - tags