# Default values for manager-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.cn-hangzhou.aliyuncs.com/choerodon/manager-service
  pullPolicy: Always

preJob:
  timeout: 300
  image: registry.cn-hangzhou.aliyuncs.com/choerodon-tools/dbtool:0.6.4
  preInitDB:
    enable: true
    datasource:
      url: jdbc:mysql://localhost:3306/manager_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: username
      password: password

deployment:
  managementPort: 8964

env:
  open:
    SPRING_DATASOURCE_URL: jdbc:mysql://localhost/manager_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    SPRING_DATASOURCE_USERNAME: username
    SPRING_DATASOURCE_PASSWORD: password
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://localhost:8000/eureka/
    CHOERODON_SWAGGER_OAUTH_URL: http://localhost:8080/oauth/oauth/authorize
    CHOERODON_GATEWAY_DOMAIN: 127.0.0.1:8080
    SPRING_REDIS_HOST: localhost
    SPRING_REDIS_PORT: 6379
    SPRING_REDIS_DATABASE: 4

    # skywalking 代理端配置
#    SKYWALKING_OPTS: >-
#      -javaagent:/agent/skywalking-agent.jar
#      -Dskywalking.agent.service_name=manager-service
#      -Dskywalking.agent.sample_n_per_3_secs=-1
#      -Dskywalking.collector.backend_service=oap.skywalking:11800

metrics:
  path: /actuator/prometheus
  label: spring-boot

logs:
  parser: spring-boot

service:
  enable: false
  type: ClusterIP
  port: 8963
  name: manager-service

resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources,such as Minikube. If you do want to specify resources,uncomment the following
  # lines,adjust them as necessary,and remove the curly braces after 'resources:'.
  limits:
    # cpu: 100m
    memory: 3Gi
  requests:
    # cpu: 100m
    memory: 2Gi